version: '3'

networks:
  object_detection:
    external: false

services:
  cvapi:
    container_name: api
    image: testdown23
    volumes:
      - "/app/models"
      - ".:/app"
    env_file: .env
    stdin_open: true # This is for using pdb
    tty: true # This is for using pdb
    ports:
      - "6000:6000"
    networks: 
      - object_detection